var messageType = {
  "3":"ISO9000审核和一核",
  "4":"内部核稿",
  "11":"核稿组一核",
  "12":"核稿组二核",
  "13":"办公室主任审核"
}
var formData = { 
  "model-437":{
    "task-3":{
      "docChar":true,
      "docYear":true,
      "emergency":true,
      "encrypt":true,
      "leader":true,
      "meeting":true,
      "mainSend":true,
      "leaderSend":true,
      "copySend":true,
      "innserSend":true,
      "manager":true,
      "subject":true
    },
    "task-4":{
      "docChar":true,
      "docYear":true,
      "emergency":true,
      "encrypt":true,
      "leader":true,
      "meeting":true,
      "mainSend":true,
      "leaderSend":true,
      "copySend":true,
      "innserSend":true,
      "subject":true
    },
    "task-6":{
      "signContent":true
    },
    "task-7":{
      "docChar":true,
      "docYear":true,
      "emergency":true,
      "encrypt":true,
      "mainSend":true,
      "leaderSend":true,
      "copySend":true,
      "innserSend":true,
      "subject":true,
      "addSign":true
    },
    "task-9":{
      "signMemo":true
    }
  }
};

var formData2 = { 
  "model-437":{
    "task-3":{
      "next":{
        "docChar":true,
        "docYear":true,
        "emergency":true,
        "encrypt":true,
        "leader":true,
        "meeting":true,
        "mainSend":true,
        "leaderSend":true,
        "copySend":true,
        "innserSend":true,
        "manager":true,
        "subject":true
      },
      "redirect":{}
    },
    "task-4":{
      "next":{
        "docChar":true,
        "docYear":true,
        "emergency":true,
        "encrypt":true,
        "leader":true,
        "meeting":true,
        "mainSend":true,
        "leaderSend":true,
        "copySend":true,
        "innserSend":true,
        "subject":true
      },
      "redirect":{}
    },
    "task-5":{},
    "task-6":{
      "internalredirect":{
        "signContent":true
      },
      "todeptleader":{},
      "next":{
        "signContent":true
      }
    },
    "task-7":{
      "next":{
        "docChar":true,
        "docYear":true,
        "emergency":true,
        "encrypt":true,
        "mainSend":true,
        "leaderSend":true,
        "copySend":true,
        "innserSend":true,
        "subject":true,
        "addSign":true
      },
      "redirect":{}
    },
    "task-8":{},
    "task-9":{
      "next":{
        "signMemo":true
      },
      "redirect":{
        "signMemo":true
      }
    }
  }
};